service: thumbnail-generator
useDotenv: true

configValidationMode: warn

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.8
  region: us-east-1
  memorySize: 512 # optional, in MB, default is 1024
  timeout: 30 # optional, in seconds, default is 6
  environment:
    STAGE: ${env:STAGE}
    THUMBNAIL_SIZE: "500"
  deploymentBucket:
    name: ${env:DEPLOYMENT_BUCKET}-${env:STAGE}
  iam:
    role:
      statements:
        - Effect: "Allow"
          Action:
            - "s3:*"
          Resource: "arn:aws:s3:::${env:PICS_UPLOADS_BUCKET}-${env:STAGE}/*"
          Sid: 'thumbnailgeneratorpersonalteachosmgeosurge'

functions:
  s3_thumbnail_generator:
    handler: handler.s3_thumbnail_generator
    events:
      - s3:
          bucket: "${env:PICS_UPLOADS_BUCKET}-${env:STAGE}"
          existing: true
          event: s3:ObjectCreated:*
          # rules:
          #   - suffix: .png

# This plugin will install all code dependencies from requirements.txt and will upload to lambda.
plugins:
  - serverless-python-requirements
  - serverless-dotenv-plugin
  - serverless-deployment-bucket # https://www.serverless.com/plugins/serverless-deployment-bucket

